const lang_en = {
  "webTitle": "PARASSET",
  //一期
  //home
  "a_diyazichanzongjiazhi": 'Total Value of Collateral Assets',
  "a_pinxingzichanzongjiazhi": 'Total Value of Parallel Assets',
  "a_baoxianchiliudongxingzongjiazhi": 'Total Value of Insurance Fund Pool',
  "a_leftmenu": [
    "Home",
    "Mint",
    "Insurance Fund Pool",
    // "Liquidate",
  ],
  "a_zhubi": 'Mint',
  "a_diyayuanshengzichan": 'Deposit Native Asset',
  "a_zhuzaopingxingzichan": 'Mint Parallel Assets',
  "a_baoxian": 'Insurance',
  "a_zhurubiaodizichantoubao": 'Deposit Underlying Asset to Insurance Fund',
  "a_zhuanqubaoxianshouyi": 'Earn Insurance Revenue',
  "a_duihuan": 'Redeem',
  "a_biaodizichanyupingxingzichan": 'Underlying Assets and Parallel Assets',
  "a_kuaisuduihuan": 'Fast Minting & Redemption',
  "a_qingsuan": 'Liquidate',
  "a_canyuzhubizhaicangqingsuanzhuanqu": 'Become a Liqidator',
  "a_zhuanquqingsuanshouyi": 'Earn Liquidation Gain',
  //mintage 铸币
  "a_zhaicang": 'Debt Position',
  "a_diyabiaodizichanshuliang": 'Underlying Assets',
  "a_yue": 'Balance',
  "a_zuida": 'MAX',
  "a_diyalv": 'Collateral Ratio',
  "a_yuyanjidiaoyongfei": 'Oracle Fee',
  "a_shouquan": 'Confirm',
  "a_qianbaokeyongyuebuzu": 'Insufficient available balance in wallet',
  "a_zhubichenggong": 'Minting success',
  "a_shouquanchenggong": 'Authorization succeeded',
  //nav top
  "a_lianjieqianbao": 'Connect Wallet',
  "a_liutongliang": ['PUSDT Circulating Supply','PETH Circulating Supply'],
  //AccountInfo
  "a_liulanqichakan": 'Browser View',
  "a_genghuanqianbao": 'Switch Wallet',
  "a_duankailianjie": 'Disconnect',
  //mintagedebt债仓
  "a_biaodizichandiyashu": 'Deposited Underlying Assets',
  "a_pingxingzichanzhubishu": 'Minted Parallel Assets',
  "a_wendingfei": 'Stability Fee',
  "a_qingsuanjiadiyalv": 'Liquidation Price | Collateral Ratio',
  "a_zhuangtai": 'Status',
  "a_caozuo": 'Action',
  "a_zhaicangqipaop1": 'Stability Fee is designed based on CR. Each debt position has to pay the stability fee according to the difference between the liquidation line and the current price and the time period when adding collateral, minting new coins, redeeming and liquidating.',
  "a_zhaicangqipaop2": 'The debt + stability fee in percentage of the value of the collateral. The risk of being liquidated increases when the current Collateral Ratio is getting close to the liquidation line.',
  "a_zhaicangqipaop3": 'The Liquidation Line equals to the Max Collateral Ratio times a multiplier. If Current Collateral Ratio ≥ Liquidation Line, the debt position can be liquidated.liquidation price =(debt + stability fee)/(liquidation line * amount of collateral)',
  "a_zhaicangqipaop4": "To be liquidated: Collateral Ratio ≥ Liquidation Line;<br/>" +
      "                          Alert: Initial Max Collateral Ratio ≤ Collateral Ratio < Liquidation Line;<br/>" +
      "                          Monitoring: 70% of Initial Max Collateral Ratio ≤ Collateral Ratio < Initial Max Collateral Ratio;<br/>" +
      "                          Healthy: Collateral Ratio < 70% of Initial Max Collateral Ratio",
  "a_daiqingsuan": 'Liquidation List',
  "a_yujing": 'Alert',
  "a_jiankong": 'Monitoring',
  "a_jiankang": 'Healthy',
  "a_diya": 'Deposite',
  "a_tiquzichan": 'Redeem',
  "a_tiqushuliang": 'Amount',
  "a_zuidaketiqu": 'MAX Redeemable',
  "a_diyazichanbiangengwei": 'New Collateral Assets',
  "a_diyalvbiangengwei": 'New Collateral Ratio',
  "a_qingsuanjiabiangengwei": 'New Liquidation Price',
  "a_jiaonawendingfei": 'Stability Fee',
  "a_quxiao": 'Cancel',
  "a_queren": 'Confirm',
  "a_zengjiadiya": 'Add Collateral',
  "a_diyashuliang": 'Amount',
  "a_keyong": 'Aviliable',
  'a_changhuan': 'Repay',
  'a_changhuanpingxingzichanshuliang': 'Repayment of Parallel Assets',
  'a_zhubizhaiwu': 'Debt',
  'a_zhubizhaiwubiangengwei': 'New Debt',
  "a_zhubishuliang": 'Amount',
  "a_zuiduokezhu": 'MAX Mintable',
  "a_diyachenggong": 'Mortgage success',
  "a_xinzengzhubichenggong": 'Successfully added coin',
  "a_tiquchenggong": 'Extracted successfully',
  "a_changhuanchenggong": 'Repaid successfully',
  //保险池 Insurance
  "a_baoxianchi": 'Insurance Fund Pool',
  "a_cong": 'From',
  "a_dao": 'To',
  "a_jiage": 'Price',
  "a_shouxvfei": 'Fee',
  "a_wodezhanbi": 'My Share',
  "a_baoxianjijinzhanghu": 'Insurance Fund Account',
  "a_jingzhi": 'Net Value',
  "a_wodebaoxianzhanghu": 'My Insurance Account',
  "a_fene": 'Share',
  "a_zhanbi": 'Proportion',
  "a_zhuru": 'Deposit',
  "a_shuhui": 'Redeem',
  "a_keshuhui": 'Redeemable',
  //清算  待清算
  "a_qingsuanyujing": 'Liquidation Alert',
  "a_daiqingsuanzichanjiazhi": 'Total Value of Assets To Be Liquidated',
  "a_yiqingsuanzichanjiazhi": 'Total Value of Liquidated Assets',
  "a_leijiqingsuanfeiyongjiazhi": 'Total Value of Liquidation Fees',
  "a_leijiqingsuanshouyi": 'Total Liquidation Gain',
  "a_yujiqingsuanchanghuanzhaiwu": 'Estimated Repayment for Liquidation',
  "a_qingsuanqipaop1": "Oracle Fee is what you pay to the NEST protocol for providing accurate market price data to the smart contract.",
  "a_qingsuanshouru": 'Liquidation Revenue',
  "a_yujiyinglijiazhi": 'Estimated Profit',
  //注入保险池 弹窗
  "a_zhurubaoxian": 'Injection of insurance',
  "a_zhurushuliang": 'Injection quantity',
  "a_dangqianjingzhi": 'The current net worth',
  "a_yujifene": 'Is expected to share',
  //赎回保险池 弹窗
  "a_shuhuibaoxian": 'Redemption of insurance',
  "a_shuhuishuliang": 'Number of redemption',
  "a_keshuhuifene": 'Redeemable share',
  "a_zuijinshuhuiri": 'Latest redemption date',
  "a_yujishuhui": 'Expected to redeem',
  "a_shengyufene": 'Residual share',
  "a_meiyoukeshuhuidezichan": 'There are no callable assets',
  //Toast 弹窗
  "a_querenzhong": 'In the confirmation',
  "a_haode": 'Good',
  "a_jiaoyiguangbozhong": 'On trade broadcast',
  "a_chakanjiaoyi": 'Check the transaction',
  "a_jiaoyichenggong": 'Transaction successfully',
  "a_jiaoyishibai": 'Transaction failed',
  "a_jiaoyiquxiao": 'Transaction cancelled',
  "a_baoxianchizichanbuzu": 'Insufficient pool assets',
  "a_qianbaoyuebuzu": 'Insufficient wallet balance',
  "a_weidaoshuhuishijian": 'It\'s not time to redeem',
}
export default lang_en
