const lang_zh = {
    "webTitle": "平行资产",
    //一期
    //home
    "a_diyazichanzongjiazhi": '抵押资产总价值',
    "a_pinxingzichanzongjiazhi": '平行资产总价值',
    "a_baoxianchiliudongxingzongjiazhi": '保险池流动性总价值',
    "a_leftmenu": [
        "首 页",
        "铸 币",
        "保 险 池",
        // "清 算",
    ],
    "a_zhubi": '铸币',
    "a_diyayuanshengzichan": '抵押原生资产',
    "a_zhuzaopingxingzichan": '铸造平行资产',
    "a_baoxian": '保险',
    "a_zhurubiaodizichantoubao": '注入标的资产投保',
    "a_zhuanqubaoxianshouyi": '赚取保险收益',
    "a_duihuan": '兑换',
    "a_biaodizichanyupingxingzichan": '标的资产与平行资产',
    "a_kuaisuduihuan": '快速兑换',
    "a_qingsuan": '清算',
    "a_canyuzhubizhaicangqingsuanzhuanqu": '参与铸币债仓清算专区',
    "a_zhuanquqingsuanshouyi": '赚取清算收益',
    //mintage 铸币
    "a_zhaicang": '债仓',
    "a_diyabiaodizichanshuliang": '抵押标的资产数量',
    "a_yue": '余额',
    "a_zuida": '最大',
    "a_diyalv": '抵押率',
    "a_yuyanjidiaoyongfei": '预言机调用费',
    "a_shouquan": '授权',
    "a_qianbaokeyongyuebuzu": '钱包可用余额不足',
    "a_zhubichenggong": '铸币成功',
    "a_shouquanchenggong": '授权成功',
    //nav top
    "a_lianjieqianbao": '连接钱包',
    "a_liutongliang": ['PUSDT 流通量','PETH 流通量'],
    //AccountInfo
    "a_liulanqichakan": '浏览器查看',
    "a_genghuanqianbao": '更换钱包',
    "a_duankailianjie": '断开连接',
    //mintagedebt债仓
    "a_biaodizichandiyashu": '标的资产抵押数',
    "a_pingxingzichanzhubishu": '平行资产铸币数',
    "a_wendingfei": '稳定费',
    "a_qingsuanjiadiyalv": '清算价 | 抵押率',
    "a_zhuangtai": '状态',
    "a_caozuo": '操作',
    "a_zhaicangqipaop1": '基于抵押率设计的稳定费，每个债仓在增 加/减少抵押、铸造新币/偿还债务及清算 时都要按照清算线和当前价格的差异、时 间周期支付稳定费。',
    "a_zhaicangqipaop2": '铸币债务+稳定费价值占抵押资产价值的百分比，当前抵押率一旦接近清算抵押率则有被清算风险。',
    "a_zhaicangqipaop3": '清算抵押率为铸币最高抵押率的一定倍数，若当前抵押率≥清算抵押率，则该债仓可被清算。清算价=(铸币债务+稳定费)/(清算抵押率*原生资产抵押数)',
    "a_zhaicangqipaop4": "待清算：抵押率≥清算抵押率；<br/>" +
        "                          预警：初始最高抵押率≤抵押率＜清算抵押率；<br/>" +
        "                          监控：初始最高抵押率的70%≤抵押率＜初始最高抵押率；<br/>" +
        "                          健康：抵押率＜初始最高抵押率的70%",
    "a_daiqingsuan": '待清算',
    "a_yujing": '预警',
    "a_jiankong": '监控',
    "a_jiankang": '健康',
    "a_diya": '抵押',
    "a_tiquzichan": '提取资产',
    "a_tiqushuliang": '提取数量',
    "a_zuidaketiqu": '最大可提取',
    "a_diyazichanbiangengwei": '抵押资产变更为',
    "a_diyalvbiangengwei": '抵押率变更为',
    "a_qingsuanjiabiangengwei": '清算价变更为',
    "a_jiaonawendingfei": '缴纳稳定费',
    "a_quxiao": '取 消',
    "a_queren": '确 认',
    "a_zengjiadiya": '增加抵押',
    "a_diyashuliang": '抵押数量',
    "a_keyong": '可用',
    'a_changhuan': '偿还',
    'a_changhuanpingxingzichanshuliang': '偿还平行资产数量',
    'a_zhubizhaiwu': '铸币债务',
    'a_zhubizhaiwubiangengwei': '铸币债务变更为',
    "a_zhubishuliang": '铸币数量',
    "a_zuiduokezhu": '最多可铸',
    "a_diyachenggong": '抵押成功',
    "a_xinzengzhubichenggong": '新增铸币成功',
    "a_tiquchenggong": '提取成功',
    "a_changhuanchenggong": '偿还成功',
    //保险池 Insurance
    "a_baoxianchi": '保险池',
    "a_cong": '从',
    "a_dao": '到',
    "a_jiage": '价格',
    "a_shouxvfei": '手续费',
    "a_wodezhanbi": '我的占比',
    "a_baoxianjijinzhanghu": '保险基金账户',
    "a_jingzhi": '净值',
    "a_wodebaoxianzhanghu": '我的保险账户',
    "a_fene": '份额',
    "a_zhanbi": '占比',
    "a_zhuru": '注入',
    "a_shuhui": '赎回',
    "a_keshuhui": '可赎回',
    //清算  待清算
    "a_qingsuanyujing": '清算预警',
    "a_daiqingsuanzichanjiazhi": '待清算资产价值',
    "a_yiqingsuanzichanjiazhi": '已清算资产价值',
    "a_leijiqingsuanfeiyongjiazhi": '累计清算费用价值',
    "a_leijiqingsuanshouyi": '累计清算收益',
    "a_yujiqingsuanchanghuanzhaiwu": '预计清算偿还债务',
    "a_qingsuanqipaop1": '你需要向NEST协议支付预言机价格使用费，以便为智能合约使用提供准确的市场价格数据。',
    "a_qingsuanshouru": '清算收入',
    "a_yujiyinglijiazhi": '预计盈利价值',
    //注入保险池 弹窗
    "a_zhurubaoxian": '注入保险',
    "a_zhurushuliang": '注入数量',
    "a_dangqianjingzhi": '当前净值',
    "a_yujifene": '预计份额',
    //赎回保险池 弹窗
    "a_shuhuibaoxian": '赎回保险',
    "a_shuhuishuliang": '赎回数量',
    "a_keshuhuifene": '可赎回份额',
    "a_zuijinshuhuiri": '最近赎回日',
    "a_yujishuhui": '预计赎回',
    "a_shengyufene": '剩余份额',
    "a_meiyoukeshuhuidezichan": '没有可赎回的资产',
    //Toast 弹窗
    "a_querenzhong": '确认中',
    "a_haode": '好的',
    "a_jiaoyiguangbozhong": '交易广播中',
    "a_chakanjiaoyi": '查看交易',
    "a_jiaoyichenggong": '交易成功',
    "a_jiaoyishibai": '交易失败',
    "a_jiaoyiquxiao": '交易取消',
    "a_baoxianchizichanbuzu": '保险池资产不足',
    "a_qianbaoyuebuzu": '钱包余额不足',
    "a_weidaoshuhuishijian": '未到赎回时间',
}
export default lang_zh
